### ISSUE TITLE
Move formatting checks from pre-commit hooks to pre-merge-requests

### ISSUE THREAD

**Issue by ohm314** [BlueBrain/hpc-coding-conventions#42]
I've been discussing some more with @matz-e and we both think that it might be a more productive and safer approach to move the clang and cmake format checks from pre-commit hooks to being executed before merge requests: On the pro side we think:
- when pre-commit hooks fail for any other reason than forgetting to quickly run the formatter before committing, can be pretty disruptive. At the same time while committing, you are still in the middle of a new feature/fix and presumably far from merging the code into the trunk of the code tree
- once you want to merge your code, it will go into the trunk of development and other people will continue from where you left of, so your code *should* be clean! So before merging it should be properly formatted.
- You don't have to rely on people being _nice_ and not simply skipping `git commit -n`. When it's enforced in the merge process, the code has to be clean before it can be merged
- You have more control over the tools, versions, environment and can make sure that the formatting/tidying is the same for all commits, regardless of the development environment

Here are some arguments on the con side:
- For big MRs you spend a lot of time doing formatting in the end, rather than early on making sure your code is clean
- Currently the pre-commit-hooks are done automagically when you include hp-coding-conventions into your project. The pre merge checks would probably have to be added manually (but only once).
- You end up with extra commits just for formatting and code cleanup (but they could/should be squashed before merge)

**Comment by tristan0x** [comment]
I could not agree more with you @ohm314 and @matz-e , **CI must ensure that contributions are properly formatted** (and run static analysis as well). This repository already allows such thing thanks to the following make targets: check-clang-format, check-cmake-format, and clang-tidy.
CI just have the enable `${PROJECT_NAME}_FORMATTING` CMake variable, and call these targets.

But to me, this and git pre-commit hooks are 2 independent things.
The hooks are not enabled by default and must be explicitly enabled by the developer, and can be disabled any time by setting the `${PROJECT_NAME}_PRECOMMIT` CMake variable back to OFF.

I agree having this enabled all the time is a pain when in the middle of a pull-request. But as a developer, I want:
1. to be able to easily call the checks that are done by CI.
1. have the possibility to have my work checked automatically for single commit contributions so that I submit code that passes CI the first time to prevent losing time going back and forth.

So unless I am mistaken, there is nothing to change in this repository' s source code.
Proper usage of the pre-commits hooks feature is missing in the documentation though. Is this what this issue is asking for?

**Comment by matz-e** [comment]
I think having the commit hooks optional is fine, so there's no requirement to change here.

Maybe we could formalize the server-side requirements. I think there would be a possibility here for a custom check process that relies only on clang (check out git repository, apply clang-format and provide feedback), without going through CMake and all required dependencies of the project.

This way, we could have a single CI setup to provide code style checks that only depends on git + clang, and is identical for all our projects.

**Comment by tristan0x** [comment]
Ideally, I would like the least server requirements as possible.

## Proposal

### hpc-coding-conventions

Add 2 CMake variables:
* `${PROJECT}_TEST_FORMATTING:BOOL`: add clang-format check to `test` make target, defaults to FALSE.
* `${PROJECT}_TEST_STATIC_ANALYSIS:BOOL`: add clang-tidy check to `test` make target, defaults to FALSE.

### spack recipes

1. spread usage below in all BBP projects using hpc-coding-conventions:
 https://github.com/BlueBrain/spack/blob/46c56c163cd0b437c96492b0fa1f3d4bbc4fb492/var/spack/repos/builtin/packages/zee/package.py#L32-L35

2. Enable the 2 CMake variables above when `@develop` or according to a certain variant,  `+ci` for instance.

**Comment by matz-e** [comment]
Enabling these variables in Spack will incur additional dependencies and variants to be tested.

## Counter-proposal

We have a `hpc-coding-conventions` module, depending on the appropriate `llvm` that provides a `check-formatting` executable script. It would be easy to integrate into CI and will not overly complicate our dependency trees.

**Comment by tristan0x** [comment]
IMO one particular aspect that I find very important is to be able as a developer to run what the CI executes. Developers working on their workstation or external collaborators would not be able to access the `hpc-coding-conventions` module. One goal the hpc-coding-conventions pursues is to provide a common base for developers and tools.

That being said, your solution @matz-e works fine with code formatting check.
But this external module reaches its limit when it comes to static analysis check with clang-tidy for instance. In this case, the tested project must drive the checking process as it knows well the compilation details (dependencies, include paths, ...).

There are open issues about code formatting check in hpc-coding-conventions and I believe your counter-proposal is also a respond so these issues. I think we should put some effort in them instead of duplicating the work.

When you mention the dependency issue, you mention the fact that all projects will have a build dependency on llvm to have clang-format and clang-tidy utility, right?
IMO it is a false problem because all C++ projects should be compiled with LLVM during CI to improve software quality. So at some point this won't be a problem anymore but the solution.
Besides because clang and gcc are ABI compatible, we don't need to build the entire llvm toolchain to test our code with llvm.

CC @pramodk

**Comment by matz-e** [comment]
> IMO one particular aspect that I find very important is to be able as a developer to run what the CI executes. Developers working on their workstation or external collaborators would not be able to access the `hpc-coding-conventions` module. One goal the hpc-coding-conventions pursues is to provide a common base for developers and tools.

The module could just be there to provide access to one common script provided by `hpc-coding-conventions`.

> When you mention the dependency issue, you mention the fact that all projects will have a build dependency on llvm to have clang-format and clang-tidy utility, right?
> IMO it is a false problem because all C++ projects should be compiled with LLVM during CI to improve software quality. So at some point this won't be a problem anymore but the solution.
> Besides because clang and gcc are ABI compatible, we don't need to build the entire llvm toolchain to test our code with llvm.

From the Spack side, I think there would be some work involved to build with LLVM while not duplicating most dependencies. Especially if projects use Python.

**Comment by tristan0x** [comment]
> > IMO one particular aspect that I find very important is to be able as a developer to run what the CI executes. Developers working on their workstation or external collaborators would not be able to access the `hpc-coding-conventions` module. One goal the hpc-coding-conventions pursues is to provide a common base for developers and tools.
> 
> The module could just be there to provide access to one common script provided by `hpc-coding-conventions`.

As I mentioned earlier, this doesn't work with static analysis. I would prefer having one solution that works for many cases than several scripts deployed here and there.

> > When you mention the dependency issue, you mention the fact that all projects will have a build dependency on llvm to have clang-format and clang-tidy utility, right?
> > IMO it is a false problem because all C++ projects should be compiled with LLVM during CI to improve software quality. So at some point this won't be a problem anymore but the solution.
> > Besides because clang and gcc are ABI compatible, we don't need to build the entire llvm toolchain to test our code with llvm.
> 
> From the Spack side, I think there would be some work involved to build with LLVM while not duplicating most dependencies. Especially if projects use Python.

If building with llvm is too much to ask for the moment, maybe we can just load module `llvm-7.0.0` in Jenkins for now to have clang-tidy and clang-format utilities.

**Comment by tristan0x** [comment]
This issue is fixed by fc9a6b38
It is not possible perform formatting checks when doing `make test`. This is already used by zee (see spack recipe).
