### ISSUE TITLE
Add CI to run cmake-format on CMake code provided, test doc generation

### ISSUE THREAD

**Issue by matz-e** [BlueBrain/hpc-coding-conventions#70]
We should automate the vetting of the CMake code and maybe re-generate the README stuff automatically/check for changes?

**Comment by tristan0x** [comment]
The CMake formatting check during the CI is already possible. To achieve that:
1. enable either the `${PROJECT}_FORMATTING:BOOL` CMake option to have both C++ and CMake formatting or only the `${PROJECT}_CMAKE_FORMAT:BOOL` option for CMake files only.
1. enable the `${PROJECT}_TEST_FORMATTING:BOOL` CMake option so that the formatting is checked when you run `make test`.
Please take a look at the [zee spack recipe](https://github.com/BlueBrain/spack/blob/develop/var/spack/repos/builtin/packages/zee/package.py), especially the `+codechecks` variant used by the CI of zee.


I am not sure to understand what you mean about the README. Could you please describe the use-case?

Regarding the documentation generation, it is not standardized yet, so it is too premature to automate this right now but I agree it should be built during the CI.
