### ISSUE TITLE
[question] Ability to provide preferred version of clang-format (and Cmake-format) for a project?

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/hpc-coding-conventions#89]
Currently we support clang-format from v7 to v11. Can I specify preferred (or exact) version required for the particular project? This will be helpful because for a particular project, we want to stick to a specific version for consistent code formatting.

**Comment by tristan0x** [comment]
`cmake -DClangFormat_EXECUTABLE=/path/to/your/favorite/clang-format ...` should do the work. I will add this in the documentation.

**Comment by tristan0x** [comment]
Ah sorry. I see know what you mean. You want a project to be able to declare "please use this clang-format version". There is nothing to do that right now. We need to make this check more generic

https://github.com/BlueBrain/hpc-coding-conventions/blob/5b871eb1d17dce1feb6cf991dbe3160b57eaeba1/cpp/CMakeLists.txt#L45-L52

to let a project override the range of desired versions

**Comment by pramodk** [comment]
> You want a project to be able to declare "please use this clang-format version". There is nothing to do that right now.

Exactly! Because someone will use clang-format 10 and others 11. Same with cmake-format. As formatting across versions is not deterministic, we need to have some way to pin the version for a give project.

**Comment by olupton** [comment]
I think we should just pin an exact version.

With `cmake-format` then different `v0.6.x` versions do not give identical results. For example, I was working with `v0.6.10` [which is required (exactly) by NEURON](https://github.com/BlueBrain/hpc-coding-conventions/blob/4c33e87ec9687c6c2f63bcd632b6868117f41c0b/cpp/CMakeLists.txt#L121) and [permitted by CoreNEURON](https://github.com/BlueBrain/hpc-coding-conventions/blob/2494c8eb72ba13ba90cb1dd3481d88148995d48b/cpp/CMakeLists.txt#L121-L125), but this is rejected by the CoreNEURON CI [which installs v0.6.13](https://github.com/BlueBrain/CoreNeuron/blob/a0bd5c9232eb8eed63fb7bb7fc37e25d20f8c2b1/.github/workflows/clang_cmake_format_check.yaml#L16-L17).

It will still be annoying if different repositories pin different versions, but at least you will find out locally that you are using the wrong version instead of having to go via the CI.

**Comment by matz-e** [comment]
With different projects requiring different versions, maybe the CMake configuration should create a virtualenv with the appropriate version itself (isolated from whatever the user may have installed), and use that?

**Comment by tristan0x** [comment]
> With different projects requiring different versions, maybe the CMake configuration should create a virtualenv with the appropriate version itself (isolated from whatever the user may have installed), and use that?

having the coding-conventions taking care of installing the tools instead of letting the user installs clang-format/cmake-format on its own might fix the issue of having dozen of versions around. coding conventions would still recommend default versions and every project would still be free to override them.
@mgeplf maintains the clang-format PyPI repo. There is only version 9 for now but we can definitely add newest versions and implement @matz-e suggestion.

**Comment by mgeplf** [comment]
> maintains the clang-format PyPI repo

Maintains is a strong word - I'm way behind on it, and haven't invested the time for OSX compat and such.  PR's definitely welcomed.

**Comment by olupton** [comment]
Auto-installing tools would be neat, although I think the system version should be preferred if it's suitable.

Updating the `clang-format` PyPI repo would be good, but the feature discussed here would already be useful for `cmake-format`.
